server:
  port: 2333
spring:
  main:
    banner-mode: "off"
    logStartupInfo: false
  application:
    name: Lavalink
logging:
  level:
    root: INFO
    lavalink: INFO
    node: INFO
    lavalink.server.io: WARN
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure: WARN
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
  sentry:
    dsn: ""
    environment: ""
sentry:
  dsn: ""
  environment: ""