services:
  bot:
    build: .
    container_name: alya
    restart: unless-stopped
    depends_on:
      - lavalink
    volumes:
      - ./:/app

  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    ports:
      - "2333:2333"
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro
