services:
  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro
    ports:
      - "2333:2333"

  bot:
    build: .
    container_name: discord_bot
    depends_on:
      - lavalink
    volumes:
      - .:/usr/src/app
